name: Deploy to AWS Lambda

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Manual Trigger

# OIDC AWS Authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Docker Buildx for caching optimizations
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # OIDC AWS Authentication Configuration
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::352326955862:role/github-actions-threadtalk-backend-role
          aws-region: ap-southeast-2

      # 1. Login to ECR Registry
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 2. Build, Tag, Push & Cache (Github server cache)
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
          # Enable caching
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      # 3. Deploy to Lambda
      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}